### ISSUE TITLE
BUG :: AssertionFailed: Field [timeline_ref] :: Value was expected to be an Identifier. 

### ISSUE THREAD

**Issue by albertgcsula** [triniti/cms-js#163]
- search timelines request is failing, need to fix the timeline_ref value.

## Steps to Reproduce
1. create a widget that can have a search request (eg gridler)
2. set the search request to be of type `teasers`
3. choose a timeline for the search request
4. save
5. make an edit
6. try to save again
7. it will fail

## Pull Request
https://github.com/triniti/cms-js/pull/164

## QA Notes
follow the steps to reproduce and confirm that you are able to save

**Comment by efjacobson** [comment]
recreated elsewhere
