### ISSUE TITLE
BUG: Styling for Save, Save & Publish, Save & Close is off

### ISSUE THREAD

**Issue by aratmz** [triniti/cms-js#2]
**Enter description**
The save, save & publish, Save & Close is off.

**Frequency**
100%

**Browser(s)**
Chrome v76

**Environment(s)**
Dev

**Device(s) Tested On**
MBP OSX 10.14.6

**Steps to Reproduce**
1. Open triniti cms 
2. Select to edit an article
3. Make some changes and observe the save button styling is off

![screen_shot_2019-10-03_at_12 03 12_pm](https://user-images.githubusercontent.com/54117171/66157480-b68e8180-e5d8-11e9-88e1-cf936df16121.png)
![screen_shot_2019-10-03_at_12 03 18_pm](https://user-images.githubusercontent.com/54117171/66157487-ba220880-e5d8-11e9-8609-5683621ada9c.png)

**Should look like this**
![screen_shot_2019-10-03_at_12 03 32_pm](https://user-images.githubusercontent.com/54117171/66157562-e0e03f00-e5d8-11e9-8b6c-755ec461ac1c.png)
![screen_shot_2019-10-03_at_12 03 35_pm](https://user-images.githubusercontent.com/54117171/66157571-e473c600-e5d8-11e9-9268-8b3ead921ca0.png)

**PR**
https://github.com/triniti/cms-js/pull/12

**QA Notes**
- observe the save button the color is correct now on hover

**Comment by nanetteCodes** [comment]
PR: https://github.com/triniti/cms-js/pull/12
